[package]
name = "lockdown-explore"
version = "0.1.0"
authors = ["David Weinstein <dweinst@insitusec.com>"]

[dependencies]
plist = "0.0.12"
glob = "*"
openssl = { git = "https://github.com/dweinstein/rust-openssl.git", branch="asn1_expiration" }
rustc-serialize = "0.3"

