[package]
name = "lockdown-explore"
version = "0.1.0"
authors = ["David Weinstein <dweinst@insitusec.com>"]

[dependencies]
plist = "0.0.12"
glob = "*"
openssl = { version = "0.8.2", features=["x509_expiry"] }
rustc-serialize = "0.3"

